from typing import Protocol

from model.position import Position
from snapshots.game_snapshot import GameSnapshot


class PlaySession(Protocol):
    """Narrow UI-facing port for local and remote play."""

    def pump(self, elapsed_ms: int) -> None: ...

    def create_snapshot(self) -> GameSnapshot: ...

    def get_selected(self) -> Position | None: ...

    def select(self, position: Position) -> None: ...

    def clear_selection(self) -> None: ...

    def request_move_to(self, target: Position) -> None: ...

    def request_jump_to(self, target: Position) -> None: ...

    @property
    def game_over(self) -> bool: ...
